accounts/urls.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy, reverse
from django.views.generic import RedirectView

from accounts.forms import TeacherRegisterForm
from accounts.models import Teacher
from accounts.views import Register, Login

urlpatterns = [
    path('', RedirectView.as_view(url='/admin'), name="admin"),
    path('student-register/<str:dept_slug>', Register.as_view(), name="stu_reg"),
    path(
        'teacher-register/',
        Register.as_view(
            model=Teacher,
            template_name="accounts/tea_reg.html",
            form_class=TeacherRegisterForm,
        ),
        name="tea_reg",
    ),
    path('login/', Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
]

api/urls.py
from django.urls import path, include
from .views import UserCreate, prof_api, UserViewSet#, GroupViewSet
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users',  UserViewSet)
# router.register(r'groups', GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('student_creation/', UserCreate.as_view()),
    path('api-auth/', 
        include('rest_framework.urls',namespace='rest_framework')
    ),
    path("for-a-prof/", prof_api),
]

lvlind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include("base.urls")),
    path('api/', include("api.urls")),
    path('account/', include("accounts.urls")),
    path('course/', include("course.urls")),
    path('department/', include("department.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import User
from django.db import models
from department.models import Department


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError("email is required")

        user = self.model(
            username=username,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.type = user.base_type
        # user.type = type
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username=username,
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField("Username", max_length=50, blank=False, unique=True)
    first_name = models.CharField("First Name", max_length=100, blank=True)
    last_name = models.CharField("Last Name", max_length=100, blank=True)
    date_of_birth = models.DateField("Date of Birth", auto_now_add=False, blank=True, null=True)
    email = models.EmailField("Email Address", blank=False, unique=True)
    pdp = models.ImageField(upload_to="users/profile", blank=True, null=True)

    sex_choice = [
        ('M', "Male"),
        ('F', "Female"),
    ]

    sex = models.CharField(max_length=1, choices=sex_choice, blank=True, default='M')

    class Type(models.TextChoices):
        ADMIN = "ADMIN", 'Admin'
        STUDENT = "STUDENT", 'Student'
        TEACHER = "TEACHER", 'Teacher'

    base_type = Type.ADMIN
    type = models.CharField(max_length=50, choices=Type.choices)

    date_joined = models.DateTimeField("date joined", auto_now_add=True)
    last_login = models.DateField("last login", auto_now=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ("username", )

    objects = MyUserManager()

    def __str__(self):
        return self.username 

    # def save(self, *args, **kwargs):
    #     if not self.pk:
    #         self.type = self.base_type
    #         return super().save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_full_name(self):
        return f'{self.last_name} {self.first_name}'


class Student(MyUser):
    dept = models.ForeignKey(Department, verbose_name="department", on_delete=models.CASCADE, blank=False)
    base_type = MyUser.Type.STUDENT
    account_id = models.PositiveBigIntegerField(unique_for_year=True, null=True)
    visa = models.IntegerField( null=False, blank=False, default=0)

    # objects = StudentManager()


class Teacher(MyUser):
    base_type = MyUser.Type.TEACHER

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Student, Teacher


class StudentRegisterForm(UserCreationForm):
    class Meta:
        model = Student
        fields = [
            "first_name",
            "last_name",
            "date_of_birth",
            "sex",
            "username",
            "email",
        ]


class TeacherRegisterForm(UserCreationForm):
    class Meta:
        model = Teacher
        fields = [
            "first_name",
            "last_name",
            "sex",
            "username",
            "email",
        ]

accounts/views.py
from django.contrib import admin
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
    
from django.urls import reverse
from django.contrib.auth import get_user_model

from accounts.forms import StudentRegisterForm
from accounts.models import Student
from department.models import Department


class Register(CreateView):
    model = Student
    template_name = "accounts/stu_reg.html"
    form_class = StudentRegisterForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sex_choice"] = Student.sex_choice
        if self.kwargs:
            context["dept"] = Department.objects.get(dept_slug=self.kwargs['dept_slug'])
        return context

    def form_valid(self, form):
        # print(form.cleaned_data)
        user = form.save(commit=False)
        user.type = user.base_type
        if user.type == "STUDENT":
            user.dept = Department.objects.get(dept_slug=self.kwargs['dept_slug'])
        return super().form_valid(form)


class Login(LoginView):
    template_name = "accounts/login.html"
    fields = "__all__"

    def get_success_url(self):
        if self.request.user.type == "ADMIN":
            return reverse_lazy("admin")
        return reverse_lazy("home")
    

class RegisterViewTestCase(TestCase):
    def setUp(self):
        # Create a sample department
        self.department = Department.objects.create(name="Sample Department")

    def test_register_view(self):
        # Ensure the register view is accessible
        response = self.client.get(reverse("register"))
        self.assertEqual(response.status_code, 200)

    def test_register_student(self):
        # Ensure a student can be registered
        data = {
            "username": "student_username",
            "email": "student@example.com",
            "password1": "student_password",
            "password2": "student_password",
            "dept": self.department.pk,
        }
        response = self.client.post(reverse("register"), data)
        self.assertEqual(response.status_code, 302)  # Should redirect after registration
        self.assertTrue(Student.objects.filter(username="student_username").exists())

    def test_register_teacher(self):
        # Ensure a teacher can be registered
        data = {
            "username": "teacher_username",
            "email": "teacher@example.com",
            "password1": "teacher_password",
            "password2": "teacher_password",
        }
        response = self.client.post(reverse("register"), data)
        self.assertEqual(response.status_code, 302)  # Should redirect after registration
        self.assertTrue(get_user_model().objects.filter(username="teacher_username").exists())

class LoginViewTestCase(TestCase):
    def setUp(self):
        self.user = get_user_model().objects.create_user(
            username="testuser",
            email="testuser@example.com",
            password="testpassword",
        )

    def test_login_view(self):
        response = self.client.get(reverse("login"))
        self.assertEqual(response.status_code, 200)

    def test_login_valid_user(self):
        data = {
            "username": "testuser",
            "password": "testpassword",
        }
        response = self.client.post(reverse("login"), data)
        self.assertEqual(response.status_code, 302)  # Should redirect after login
        self.assertEqual(response.url, reverse("home"))

    def test_login_admin_user(self):
        self.user.type = Student.Type.ADMIN
        self.user.save()
        data = {
            "username": "testuser",
            "password": "testpassword",
        }
        response = self.client.post(reverse("login"), data)
        self.assertEqual(response.status_code, 302)  # Should redirect after login
        self.assertEqual(response.url, reverse("admin"))

    def test_login_invalid_user(self):
        data = {
            "username": "invaliduser",
            "password": "invalidpassword",
        }
        response = self.client.post(reverse("login"), data)
        self.assertEqual(response.status_code, 200)  # Should stay on the login page


accounts/templates/accounts/login.html
{% extends 'base/header.html' %}
{% load static %}

    {% block style %}
        <link rel="stylesheet" href="{% static 'accounts/css/loginn.css' %}">
    {% endblock %}
    {% block home_link %}
        href="{% url 'index' %}"
    {% endblock %}
    {% block about_link %}
        href="{% url 'index' %}#about"
    {% endblock %}
    {% block formation_link %}
        href="{% url 'index' %}#formation"
    {% endblock %}
    {% block actus_link %}
        href="{% url 'index' %}#actus"
    {% endblock %}
    {% block contact_link %}
        href="{% url 'index' %}#contact"
    {% endblock %}


{% block header_content %}
    <div class="login">
        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            {{form}}

            <input type="submit" value="LOGIN">
        </form>
        <p>Don't have an account&nbsp;<a href="{% url 'index' %}#formation">Register</a></p>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>student-register</title>
</head>
<body>
    <h1>STUDENT REGISTER</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>

accounts/templates/accounts/stu_home.html
{% extends 'base/home.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/stu_home.css' %}">
{% endblock %}

{% block script %}
    <script defer src="{% static 'accounts/js/stu_homeeee.js' %}"></script>
{% endblock %}


{% block content %}
    <div class="stu_container">
        <main class="stu_main">
            <div class="new_courses">
                <h4 class="new_course_ahead">New Courses:</h4>
                <div class="new_course_slide">
                    {% for course in new_courses %}
                        <a href="{% url 'course_detail' course.subject.subject_slug course.slug %}">
                            <div class="new_course_cover"></div>
                            <div class="new_course_info">
                                <div class="info_top">
                                    <h4>{{ course.title }}</h4>
                                    <span>{{ course.subject }}</span>
                                </div>
                                <div class="info_bottom">
                                    <div class="left_info">
                                        <span>{{ course.subject.teacher.get_full_name }}</span>
                                    </div>
                                    <div class="right_info">
                                        <span class="date">{{ course.date_upload|date:"d M Y" }}</span>
                                        <span class="hour">{{ course.date_upload|date:"H:i" }}</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="course_list_container">
                <h4>
                    <span>My Courses:</span>&nbsp;&nbsp;
                    <span class="subject_title">All</span>
                </h4>
                <div class="table_header row">
                    <span class="col col1">Title</span>
                    <span class="col col2">Date</span>
                    <span class="col col3">Hour</span>
                    <span class="col col4">present</span>
                </div>
                <div class="course_list_wrap">
                    <div class="course_list">
                        {% for course in courses %}
                            <a href="{% url 'course_detail' course.subject_slug course.slug %}" class="course row">
                                <span class="col col1">{{ course.title }}</span>
                                <span class="col col2">{{ course.date }}</span>
                                <span class="col col3">{{ course.hour }}</span>
                                <span class="col col4">
                                    {% if course.presence %}
                                        <i class="ri-check-double-line present"></i>
                                    {% else %}
                                        <i class="ri-close-line absent"></i>
                                    {% endif %}
                                </span>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </main>
        <aside class="aside_container">
            <div class="subject_list">
                <header>
                    <h4>Subjects:</h4>
                </header>
                <main>
                    <div class="aside_link">
                        {% for subject in subjects %}
                            <a class="sbj_btn" href="{% url 'course_list' subject_slug=subject.subject_slug %}" id="{{ subject }}">
                                <div class="fond" id="{{ subject }}"></div>
                                <div id="{{ subject }}">
                                    <h4 id="{{ subject }}">{{ subject }}</h4>
                                    <span class="subject_prof">{{ subject.teacher.get_full_name }}</span>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </main>
            </div>
        </aside>
    </div>    
{% endblock %}

accounts/templates/accounts/stu_reg.html
{% extends 'base/header.html' %}
{% load static %}

    {% block style %}
        <link rel="stylesheet" href="{% static 'accounts/css/registerr.css' %}">
    {% endblock %}
    {% block script %}
        <script defer src="{% static 'accounts/js/registerrr.js' %}"></script>
    {% endblock %}

    {% block home_link %}
        href="{% url 'index' %}"
    {% endblock %}
    {% block about_link %}
        href="{% url 'index' %}#about"
    {% endblock %}
    {% block formation_link %}
        href="{% url 'index' %}#formation"
    {% endblock %}
    {% block actus_link %}
        href="{% url 'index' %}#actus"
    {% endblock %}
    {% block contact_link %}
        href="{% url 'index' %}#contact"
    {% endblock %}

{% block header_content %}
    <div class="register">
        <h1>Register to {{ dept }}</h1>
        <div class="progressbar">

            <div class="progress"></div>

            <div class="progress_step">
                <i class="ri-file-user-line"></i>
            </div>
            <div class="progress_step">
                <i class="ri-user-line"></i>
            </div>
            <div class="progress_step">
                <i class="ri-visa-fill"></i>
            </div>
            <div class="progress_step">
                <i class="ri-lock-2-line"></i>
            </div>

        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form_step">
                <div class="input_group">
                    <label for="f_name">First Name</label>
                    <input type="text" name="first_name" id="f_name">
                </div>
                <div class="input_group">
                    <label for="l_name">Last Name</label>
                    <input type="text" name="last_name" id="l_name">
                </div>
                <div class="input_group">
                    <label for="dob">Date of Birth</label>
                    <input type="date" name="date_of_birth" id="dob">
                </div>
                <div class="input_group sexe">
                    <div>
                        <input type="radio" name="sex" id="{{sex_choice.0.1}}" value="{{sex_choice.0.0}}" checked>
                        <label for="{{sex_choice.0.1}}">
                            {{sex_choice.0.1}}
                            <div class="radio radio_masculin">
                                <i class="ri-checkbox-blank-circle-line"></i>
                                <i class="ri-radio-button-line"></i>
                            </div>
                        </label>
                    </div>
                    <div>
                        <input type="radio" name="sex" id="{{sex_choice.1.1}}" value="{{sex_choice.1.0}}" >
                        <label for="{{sex_choice.1.1}}">
                            <div class="radio radio_feminin">
                                <i class="ri-checkbox-blank-circle-line"></i>
                                <i class="ri-radio-button-line"></i>
                            </div>
                            {{sex_choice.1.1}}
                        </label>
                    </div>
                </div>
                <div class="btn_container">
                    <a href=""  class="btn btn-next">
                        &nbsp;&nbsp;&nbsp;  Next &nbsp;
                        <i class="ri-arrow-right-line"></i>
                    </a>
                </div>
            </div>
            <div class="form_step">
                <div class="input_group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username">
                </div>
                <div class="input_group">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email">
                </div>
                <div class="btn_container">
                    <a href="" class="btn btn-prev">
                        <i class="ri-arrow-left-line"></i>
                        &nbsp; Prev
                    </a>
                    <a href=""class="btn btn-next">
                        Next &nbsp;
                        <i class="ri-arrow-right-line"></i>
                    </a>
                </div>
            </div>
            <div class="form_step">
                <div class="input_group">
                    <label for="id_visa">VISA CARD</label>
                    <input type="number" name="visa" id="id_visa" max="9999,9999,9999" min="999,9999,9999">
                </div>
                <div class="input_group">
                    <label for="id_password"> Visa Password</label>
                    <input type="password" name="password1" id="id_password">
                </div>
                <div class="btn_container">
                    <a href="" class="btn btn-prev">
                        <i class="ri-arrow-left-line"></i>
                        &nbsp; Prev
                    </a>
                    <a href=""class="btn btn-next">
                        Next &nbsp;
                        <i class="ri-arrow-right-line"></i>
                    </a>
                    
                </div>
            </div>
            <div class="form_step">
                <div class="input_group">
                    <label for="id_password1">Password</label>
                    <input type="password" name="password1" id="id_password1">
                </div>
                <div class="input_group">
                    <label for="id_password2">Password Confirmation</label>
                    <input type="password" name="password2" id="id_password2">
                </div>
                <div class="btn_container">
                    <a href="" class="btn btn-prev">
                        <i class="ri-arrow-left-line"></i>
                        &nbsp; Prev
                    </a>
                    <span class="btn btn-done">
                        <input type="submit" id="submit" value="Done">
                        <label for="submit">
                            <i class="ri-check-double-line"></i>
                        </label>
                    </span>

                </div>
            </div>
            
        </form>
    </div>
    
{% endblock %}

accounts/templates/accounts/tea_home.html
{% extends 'base/home.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/tea_home.css' %}">
{% endblock %}

{% block script %}
    <script defer src="{% static 'accounts/js/tea_homee.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="tea_block">

        <main class="courses_container">
            <div class="course_list_container">
                <header class="course_header">
                    <h4>Courses:&nbsp;
                        <span>All</span>
                    </h4>
                </header>
                <div class="course_header_table row">
                    <span class="col col1">Title</span>
                    <span class="col col2">Date</span>
                    <span class="col col3">Hour</span>
                </div>
                <div class="course_list">
                    {% for course in courses %}
                        <a href="{{ course.url }}" class="row" style="text-decoration: none;">
                            <span class="col col1">{{ course.title }}</span>
                            <span class="col col2">{{ course.date }}</span>
                            <span class="col col3">{{ course.hour }}</span>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </main>
        <aside class="aside_container">
            <div class="aside_content">
                <header class="aside_header">
                    <h4>taught sector</h4>
                </header>
                <main class="dept_container">
                    <div class="dept_content">
                        <ul>
                            {% for dept in depts %}
                                <li>
                                    <div class="dept" id="{{ dept.slug }}">
                                        <div class="img" 
                                            style="background-image: url({{dept.cover_url}});" id="{{ dept.slug }}">
                                        </div>
                                        <div class="dept_desc" id="{{ dept.slug }}">
                                            <label id="{{ dept.slug }}">{{ dept.name }}</label>
                                            <p id="{{ dept.slug }}">{{ dept.nbr_stu }}&nbsp;Students
                                                <h6>New 8 courses</h6>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="{{ dept.slug }}_container subjects_container">
                                        <ul class="{{dept.slug}} subjects">
                                        </ul>
                                    </div>
                                </li>
                                {{ room_name|json_script:"room-name" }}
                                <script>
                                    const roomName = JSON.parse(document.getElementById('room-name').textContent);
                                    const notificationSocket = new WebSocket(
                                        'ws://'+ window.location.host
                                        + '/ws/notification/'+roomName+'/'
                                    );
                                    
                                    console.log(notificationSocket);
                                    
                                    notificationSocket.onmessage = function(e) {
                                        const data = JSON.parse(e.data);
                                        //document.querySelector('#chat-log').value += (data.message + '\n');
                                        console.log(data);
                                        //document.getElementById("notifications-dropdown").innerHTML = "<li class='dropdown-item'>" + data + "</li><hr class='dropdown-divider'>" + document.getElementById("notifications-dropdown").innerHTML;
                                        //document.getElementById("notification-badge").innerHTML = parseInt(document.getElementById("notification-badge").innerHTML) + 1;
                                    };
                                    notificationSocket.onclose = function(e) {
                                        console.error('Chat socket closed unexpectedly');
                                    };
                                </script>
                            {% endfor %}
                        </ul>   
                    </div>
                </main>
            </div>
        </aside>
    </div>
    

{% endblock %}

{% block modal %}
    <div class="create_course_wrap">
        <div class="create_course_container">
            <header class="create_course_header">
                <h3>Add course</h3>
            </header>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input_group course_title">
                    <label for="course_title">Title</label>
                    <input type="text" id="course_title" name="title">
                </div>
                <div class="input_group course_desc">
                    <label for="course_desc">Description</label>
                    <textarea type="text" id="course_desc" name="description"></textarea>
                </div>
                <div class="input_group course_video">
                    <label for="course_video" class="course_video_input">
                        <div class="label">Video</div>
                        <div class="input_file">
                            <p class="result_file">No video selected</p>
                            <span class="input_file_btn">
                                <i class="ri-upload-line"></i>
                                Browse
                            </span>
                        </div>
                    </label>
                   <input type="file" id="course_video" name="video" style="display: none;">
                </div>
                <input type="submit" value="SAVE">
            </form>
        </div>
            <button class="btn_close" id="btn_close">
                <i class="ri-close-line" id="btn_close"></i>
            </button>
    </div>
{% endblock %}

<!-- Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur corrupti neque necessitatibus dolorum optio sed praesentium tempore. Nam, ut possimus. -->

accounts/templates/accounts/tea_reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>teacher-register</title>
</head>
<body>
    <h1>TEACHER REGISTER</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>